server:
  port: 8080
spring:
  application:
    name: daisyday-project-elasticsearch
  jackson:
    default-property-inclusion: non_null  # JSON返回值去除null和空字段
    serialization:
      write-dates-as-timestamps: true  # JSON返回时间为时间戳格式
  datasource:
    db2:
      ##########################  mysql   ##########################
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: core_test
      password: sunsoft@toponebuy
      url: jdbc:mysql://sh-cdb-87po6krs.sql.tencentcdb.com:62816/a_top_one_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      ##########################  druid_pool_config ##########################
      initial-size: 5                                        #连接池建立时创建的初始化连接数
      max-active: 20                                         #连接池中最大的活跃连接数
      min-idle: 5                                            #连接池中最小的活跃连接数
      max-wait: 60000                                        #配置获取连接等待超时的时间
      pool-prepared-statements: true                         #打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20    #打开PSCache，并且指定每个连接上PSCache的大小
      test-on-borrow: false                                  #是否在获得连接后检测其可用性
      test-on-return: false                                  #是否在连接放回连接池后检测其可用性
      test-while-idle: true                                  #是否在连接空闲一段时间后检测其可用性
  data:
    elasticsearch:
      cluster-name: elasticsearch #elasticsearch集群名称，默认的是elasticsearch
      cluster-nodes: 118.25.71.42:9300  #节点的地址 注意api模式下端口号是9300，千万不要写成9200
      repositories:
        enabled: true #是否开启本地存储

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://jixiangtest:jixiangtest2019@localhost:7001/eureka
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        # spring-boot-starter-actuator 2.0版本以上得这么配置，将接口暴露出来，如果要暴露全部节点使用include: "*"
        include: refresh,health,info
  health:
    mail:
      enabled: false
    elasticsearch:
      enabled: false
# INFO ENDPOINT CONFIGURATION
info:
  java:
    version: ${java.version}
  app.name: ${spring.application.name}
  company.name: www.toponebuyer.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
sunsoft:
  email:
    toUser:
    coypUser: Tiki.wang@groupjx.com,dymdoudou@126.com,cmj15216802114@126.com
  file:
    bill:
      pdf:
        path: C:\Users\Administrator\Desktop\export_file\pdf\
      excel:
        path: C:\Users\Administrator\Desktop\export_file\excel\

